name: Android Release CI

on:
  push:
    branches: [ "http-server-version" ]

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find APK
        id: find_apk
        run: |
          APK_FILE=$(find app/release -name "ZTE-UFI-TOOLS*.apk" | head -n 1)
          if [ -z "$APK_FILE" ]; then
            echo "APK file not found!"
            exit 1
          fi
          echo "APK_PATH=$APK_FILE" >> $GITHUB_ENV
          echo "apk_path=$APK_FILE" >> $GITHUB_OUTPUT
      - name: Generate timestamp tag
        id: tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d-%H%M%S')"
          echo "Generated tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}